### ISSUE TITLE
Services.jar dex file not generated on Samsung Marshmallow build

### ISSUE THREAD

**Issue by wanam** [rovo89/Xposed#105]
I'm trying to get Xposed to boot up on Samsung Marshmallow FW, i made the required art changes to get dex2oat to run with no apparent issues, but i'm stuck with a strange error after boot.oat dexopting:

> 12-27 19:16:52.530  3921  3921 E Zygote  : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.server.SystemServer" on path: DexPathList[[zip file "/system/framework/services.jar", zip file "/system/framework/services.jar", zip file "/system/framework/ethernet-service.jar", zip file "/system/framework/wifi-service.jar"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
> 12-27 19:16:52.530  3921  3921 E Zygote  : 	Suppressed: java.io.IOException: No original dex files found for dex location /system/framework/services.jar

Here are the full logs: https://www.dropbox.com/s/5soaodtw5joltw8/logmm5.zip?dl=0

It's seems somehow the dex file of services.jar is not generated (many other framework dex files as well), maybe a class-path issue, i'm not sure about that, here is the class-path settings https://www.dropbox.com/s/ydhswjitklelace/init.environ.rc?dl=0

I'm getting the same result after trying to deodex it with https://github.com/testwhat/SmaliEx  with Svadev tool, no dex file is generated for services.jar.

Here is the framework: https://www.dropbox.com/s/3k6t41w1u6wk0un/framework-tw-mm.zip?dl=0

@rovo89 any ideas where i should check?

**Comment by wanam** [comment]
It was my fault, installd does not require odex renaming anymore to run dex2oat.
Sorry for disturbing.

**Comment by Bryan2Lee** [comment]
Hi, Wanam, I am dealing with the same issue right now? would you please teach me how solve this issue?
My exceptions are as following, which happens when the system is booting(the systemserver crashes):
--------------------------------------------------------------------------------------------------------------
--------- beginning of crash
01-01 00:00:29.997 E/AndroidRuntime( 3755): *** FATAL EXCEPTION IN SYSTEM PROCESS: main
01-01 00:00:29.997 E/AndroidRuntime( 3755): java.lang.RuntimeException: Missing class when invoking static main com.android.server.SystemServer
01-01 00:00:29.997 E/AndroidRuntime( 3755): 	at com.android.internal.os.RuntimeInit.invokeStaticMain(RuntimeInit.java:260)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 	at com.android.internal.os.RuntimeInit.applicationInit(RuntimeInit.java:381)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 	at com.android.internal.os.RuntimeInit.zygoteInit(RuntimeInit.java:333)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 	at com.android.internal.os.ZygoteInit.handleSystemServerProcess(ZygoteInit.java:502)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 	at com.android.internal.os.ZygoteInit.startSystemServer(ZygoteInit.java:589)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:670)
01-01 00:00:29.997 E/AndroidRuntime( 3755): Caused by: java.lang.ClassNotFoundException: com.android.server.SystemServer
01-01 00:00:29.997 E/AndroidRuntime( 3755): 	at java.lang.Class.classForName(Native Method)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 	at java.lang.Class.forName(Class.java:324)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 	at com.android.internal.os.RuntimeInit.invokeStaticMain(RuntimeInit.java:258)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 	... 5 more
01-01 00:00:29.997 E/AndroidRuntime( 3755): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.server.SystemServer" on path: DexPathList[[zip file "/system/framework/services.jar", zip file "/system/framework/ethernet-service.jar", zip file "/system/framework/wifi-service.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
01-01 00:00:29.997 E/AndroidRuntime( 3755): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 	... 8 more
01-01 00:00:29.997 E/AndroidRuntime( 3755): 	Suppressed: java.io.IOException: No original dex files found for dex location /system/framework/services.jar
01-01 00:00:29.997 E/AndroidRuntime( 3755): 		at dalvik.system.DexFile.openDexFileNative(Native Method)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 		at dalvik.system.DexFile.<init>(DexFile.java:80)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 		at dalvik.system.DexFile.<init>(DexFile.java:59)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:279)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:38)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 		at com.android.internal.os.ZygoteInit.handleSystemServerProcess(ZygoteInit.java:495)
01-01 00:00:29.997 E/AndroidRuntime( 3755): 		... 2 more
