### ISSUE TITLE
After flashing I got some FCs.

### ISSUE THREAD

**Issue by dzej1** [rovo89/Xposed#114]
Until I flashed xposed was everything fine, when I flashed it apps like Bluetooth, Downloads started at open crashing. When I uninstall xposed is again everything fine. 

My device is Nexus 5X with stock rom, franco.Kernel, system-less root, decrypted. 

Log: https://drive.google.com/file/d/0B757zZ_qcyFbLUdEQ1UxSmUtR0U/view?usp=docslist_api

**Comment by xXCooL69GuYXx** [comment]
Do a stock factory restate
On Jan 17, 2016 1:58 PM, "dzej1" <notifications@github.com> wrote:
>
> Until I flashed xposed was everything fine, when I flashed it apps like
Bluetooth, Downloads started at open crashing When I uninstall xposed is
again everything fine
>
> My device is Nexus 5X with stock rom, francoKernel, system-less root,
decrypted
>
> Log:
https://drivegooglecom/file/d/0B757zZ_qcyFbLUdEQ1UxSmUtR0U/view?usp=docslist_api

**Comment by dzej1** [comment]
I did it three times, still with same result

**Comment by rovo89** [comment]
Do you get an "optimizing" dialog after each reboot?

**Comment by dzej1** [comment]
Okay, I wiped cache and dalvik after flashing, odex'll be recreated and everything works fine. Maybe you could add post-wiping after flashing xposed.

**Comment by rovo89** [comment]
Let me clarify a few things:

- odex files and the oat files in the Dalvik cache have the same format, it's just a different extension.
- These files have a header with some checksums and also an Xposed-specific file format number (not the Xposed version!)
- Even AOSP ART detects when one of these fields has changed and triggers a recompilation of the oat files. Xposed just adds its own file format number to the criteria.
- Therefore, it shouldn't be necessary to clear the Dalvik cache manually. I don't want to do that from the installation ZIP because then it would clear the cache whenever you update Xposed, even when there was no change in the file format. It would also require to mount /data r/w.

If for some reason the oat files were not regenerated, I would need a log with more information. The one you posted starts a bit too late, the regeneration would already be over at that point.

I'll leave it up to you. If you're willing to reproduce the issue and post a new log, it would be good. If not, please close this issue, then we'll wait whether others run into the same issue.

**Comment by dzej1** [comment]
Now I'm fine, in case i'm getting again that FCs will imediately send log here, for now i'm closing.
