### ISSUE TITLE
Boot loop on huawei mediapad x2 (GEM-703L) runing android 5.0 original rom

### ISSUE THREAD

**Issue by khezr94** [rovo89/Xposed#122]
Flashing the framework ( I tried v79 & v80) couse boot loop, so after I start the device its booting take 2-3 minutes more than former (showing huawei brand).
It just show the locked homescreen (without signals) and when I unlock the screen it becomes black

**Comment by khezr94** [comment]
From which address can I found the log file? Can Anyone help me?

**Comment by rovo89** [comment]
If you see the lockscreen, it's not a bootloop.
Please make sure that you don't have any modules enabled, e.g. by deleting `/data/data/de.robv.android.xposed.installer/conf/modules.list`.
In order to take a logcat, execute as early as possible: `adb logcat -v time > logcat.txt`. Then wait until the device has booted (and the screen becomes black) and press Ctrl+C.

**Comment by khezr94** [comment]
Ok thnx for answering, I do it immediatly

**Comment by khezr94** [comment]
The conf folder is empty,
as you said I flashed the framework v80 then I connected my device to pc, and turned it on, after unlocking screenlock the screen became black and then I gate this logcat.
I must add that whenever I lock the screen again, it show lockscreen correctly( without operator logo and signals)

**Comment by khezr94** [comment]
[logcat.txt](https://github.com/rovo89/Xposed/files/124891/logcat.txt)

**Comment by rovo89** [comment]
Looks like #72

**Comment by khezr94** [comment]
So what could be the reason of this issue?

**Comment by khezr94** [comment]
There is no other way?
I just want xposed for its lucky pacher module

**Comment by rovo89** [comment]
Please don't discuss illegal stuff here.
