### ISSUE TITLE
Minimize / eliminate /system changes

### ISSUE THREAD

**Issue by Fuzion24** [rovo89/Xposed#126]
The Android linker has default library path that it searches when trying to load up a shared library required by another application or library: [https://github.com/android/platform_bionic/blob/lollipop-release/linker/linker.cpp#L9://github.com/android/platform_bionic/blob/lollipop-release/linker/linker.cpp#L96](Default LD Paths).  In order to be able to inject code in applications, we want to choose a library which is linked into almost all apps.  ```/system/lib/liblog.so``` is a good choice as it is a small library that nearly every binary links against. Since, ```/vendor/lib``` is on the linker's library search path before ```/system/lib/```, if we create a ```/vendor/lib/liblog.so``` it will get linked instead of ```/system/log/liblog.so```.

After installing Substrate, we can see this behaviour of creating a new liblog.so which is just a pointer to libAndroidBootstrap0.so:

```
root@flo:/vendor/lib # ls -l | grep log
lrwxrwxrwx root     root              2014-11-25 08:34 liblog!.so -> /system/lib/liblog.so
lrwxrwxrwx root     root              2014-11-25 08:34 liblog.so -> /data/data/com.saurik.substrate/lib/libAndroidBootstrap0.so
```

Applications and libraries still attempt to call functions from the original liblog.so, which means that ```libAndroidBootstrap0.so``` will have to proxy these calls through to the original liblog.so library. We can see the symbols that we are going to need to proxy by using nm:

```
arm-linux-androideabi-nm -D liblog.so  | grep T
0000146c T __android_log_assert
00001500 T __android_log_btwrite
0000140c T __android_log_buf_print
00001244 T __android_log_buf_write
000014d8 T __android_log_bwrite
000010e8 T __android_log_dev_available
000013b0 T __android_log_print
00001364 T __android_log_vprint
00001128 T __android_log_write
00002072 T android_closeEventTagMap
000018c8 T android_log_addFilterRule
000019c8 T android_log_addFilterString
000017cc T android_log_formatFromString
00001bd0 T android_log_formatLogLine
000017aa T android_log_format_free
00001796 T android_log_format_new
00001eac T android_log_printLogLine
00001aa8 T android_log_processBinaryLogBuffer
00001a1c T android_log_processLogBuffer
000017c8 T android_log_setPrintFormat
00001764 T android_log_shouldPrintLine
0000243c T android_lookupEventTag
0000208c T android_openEventTagMap
00001f64 T logprint_run_tests
```

The replacement liblog.so in ```/vendor/lib``` dynamically opens (dlopen) the original liblog.so, finds the symbol of interest and stores the handle as a global variable. Doing this would allow you to not have to copy / duplicate the code for app_process, but rather inject it dynamically.  From looking at your changes to art, i dont think it'd be possible to dynamically proxy it, but could be interesting.

It could go a long way in helping with a minimal impact, systemless implementation :  http://forum.xda-developers.com/showthread.php?p=65113226#post65113226

**Comment by Fuzion24** [comment]
Here's a stab at writing the liblog wrapper (currently buggy/not functioning) -- 
```
➜  hooker git:(dev) ✗ cat jni/log.c | gist -p
https://gist.github.com/71238dbf67db23f6438b
```

**Comment by rovo89** [comment]
It's an interesting approach, but apart from the fun of exploring it, what's the ultimate goal? Do you want to keep /system modification-free in order to keep OTAs working? Or do you want to patch the system files on-the-fly instead of overwriting them with prebuilt copies in order to keep vendor-specific coding working?

For the former, I think there are better ways, e.g. using bind mounts. They're not easy either, but more straight-forward. As `/vendor/` is often just a symlink to `/system/vendor`, there would be modifications anyway. If it's a normal partition, I guess it will be checked by OTAs as well.

For the latter, I doubt that it will be possible, and if it does, I think it will be a lot harder to maintain and keep compatible. The ART changes definitely can't be patched into the existing libraries and binaries, especially not if the vendor has made any bigger changes compared to AOSP. That basically leaves `app_process`, which is rarely ever changed in AOSP and therefore is a very low-risk replacement: https://github.com/android/platform_frameworks_base/commits/master/cmds/app_process
Additionally, I'm not sure if SELinux would allow writing to executable memory.

Anyway, I'm looking forward to hear your opinion what you'd like to achieve and how exactly. Assuming the liblog wrapper was working now, what would be your next steps?

**Comment by rovo89** [comment]
Closed due to lack of response.
