### ISSUE TITLE
Frequent boot freezes on Nexus 5 / OmniROM

### ISSUE THREAD

**Issue by F-i-f** [rovo89/Xposed#152]
I am seeing frequent boot freezes on a Nexus 5 device running:
- OmniROM 6.0.1 20160416 (Marshmallow)
- Xposed v83 arm
- The device is encrypted if it makes a difference.

This is not a new issue, I've been seeing as early as v89.
The symptom is that when I power-up the device, or I reboot:
- The device starts normally
- I'm asked for my /data encryption password.
- The boot resumes but never completes.

This happens about half of the time on my device.  Some times I go through a few reboots without any issues, other times I hit 3 or 4 successive reboots that get stuck.
It seems that if the power is plugged in, I have a higher chance of hitting the issue (as high as 75% of reboots do not complete).

The usual fix for these problems is to wipe the Dalvik cache and reboot.
When I do this, the system sometimes reboots successfully, sometimes not.
So in effect, wiping the Dalvik Cache does not help.

Now to this specific test case:
When I upgraded to Xposed v83, I:
- dirty flashed v83 on top of v82
- wiped the dalvik cache
- rebooted
- the boot hung after the encryption password was entered.
- I then rebooted into recovery
- I turned on ADB debugging
- I wiped the Dalvik cache
- I then rebooted into the system, capturing a backtrace
- the boot hung again.

I've attached to this bug the 'adb logcat' as well as the 'dmesg' from this attempt.
[dmesg.txt](https://github.com/rovo89/Xposed/files/246080/dmesg.txt)
[logcat.txt](https://github.com/rovo89/Xposed/files/246081/logcat.txt)

The logcat does not tell me much except that the process is stuck somewhere.
There are some scary SELinux AVC messages about not being able to access the dalvik-cache, I'm not sure if these are normal or not.

**Comment by rovo89** [comment]
Thanks for the detailed bug report, it's always helpful to get all the details.

I can think of mainly two reasons why the boot process simply gets stuck that early:
- There's an endless loop.
- There's a background thread running. Zygote doesn't seem to like that.

I also noticed that the "am" command is starting every half a minute, that's also unusual.

As you mentioned that this happens regularly, could you please test it for some time without any modules enabled? Any one of them could easily be the culprit here.

**Comment by F-i-f** [comment]
I just disabled all modules, rebooted 5 times in a row without a hang.
After reenabling all the modules, the first boot hung, and the second was successful.
We may be onto something here :-)

I am able to get a root shell on the device at the point where it's hung.
Is there anything I could there to catch the offending module?
I'd loath to bisect my somewhat large module list to identify the modules that cause issues...

**Comment by idlukakas** [comment]
I also confirm my Nexus 5 bootloop frequently after install Xposed V83 arm.

[[cm13caf][unofficial][-o3 optimization] - 20160430
Xposed v83 arm
The device is not encrypted.
Wiping the Dalvik Cache does not work.

Now to this specific test case:
When I upgraded to Xposed v83, I:
dirty flashed v83 on top of v82
wiped the dalvik cache
rebooted withou success.

I reverted back do v82 without problems.

**Comment by F-i-f** [comment]
@idlukakas : Interesting...  Were you able to capture a logcat?  Which modules did you have enabled?  When Xposed gets into a bootloop like this, I can generally get it to work by reentering recovery and clearing dalvik again.  At the worst times (happened when I installed v83), I've had to do this 3 times in a row to get it to boot.

Now to v84:
v84 has been very good for me.
I must have rebooted the device at least 15 times since I've updated and the boot only froze once.
That freeze however happened just after I had removed a priv-app system APK, which is not very common.  Unfortunately, I had USB Debug off and wasn't able to capture the logcat.

**Comment by idlukakas** [comment]
I just disable XHFW3 module and works fine now.

**Comment by F-i-f** [comment]
Great for you :-)  
On my side, I didn't have XHFW3 installed.

**Comment by rovo89** [comment]
> I just disabled XHFW3 module and works fine now.

Thanks, I'll try to reproduce it. I can already see that the module isn't compiled correctly: https://github.com/shooash/XHFW3/blob/master/app/build.gradle#L24
Which module version did you have issues with?

> On my side, I didn't have XHFW3 installed.

Were you able to find out whether any particular module was the culprit?

**Comment by idlukakas** [comment]
3.13 version. I just reinstalled that module again and worked when wiped cache.

I have no idea now.

http://forum.xda-developers.com/showpost.php?p=66738103&postcount=67

http://forum.xda-developers.com/showpost.php?p=66741030&postcount=70

**Comment by rovo89** [comment]
That's all very strange... I can reproduce a hanging boot with XHFW3 on Nexus 5, CM13, Xposed v82. It's hanging only sometimes though.

One theory I have is that there are indeed some threads still running. The module doesn't do really much in Zygote, except for reading four preference files. I'll try to debug further to find out whether there's a racing condition due to which this file reading sometimes gets stuck and leaves a thread running. Might also be a thread synchronization issue... I'm really not sure.

Regarding my assumption that the module isn't compiled properly: The APK seems to be OK, even though the build settings clearly say that the Xposed API would be compiled into the APK (instead of just being referenced). Maybe something else fixes this (e.g. ProGuard).

**Comment by F-i-f** [comment]
>>  On my side, I didn't have XHFW3 installed.

> Were you able to find out whether any particular module was the culprit?

No, I didn't.  Just after I've opened this bug, Xposed v84 came out, which I upgraded to.
And as I was reporting earlier, it's not happening as often anymore, which makes it way harder to find the offending module. 
Since the v84 upgrade, I've had a grand total of two hangs out of thirty reboots on 3 devices.  The hangs happened on a Nexus 4 (doing nothing special, just rebooted from a Recovery session) and a Nexus 5 (reported in [a comment above](https://github.com/rovo89/Xposed/issues/152#issuecomment-217644515)). Both devices were running the exact same software stack (ROM/Xposed/modules).

I've seen these issues since at least Xposed v89 on MM with a variety of ROMs (CM, Omni) and a variety of devices (Nexus 4 and Nexus 5).  It's also very elusive.
Sometimes three reboots in a row will hang.  Some other times, I can reboot many times without a hitch.

Happy to do more testing, time permitting of course, but you seem to have a semi-reproducible test case with a single module, which should be easier to debug.

**Comment by F-i-f** [comment]
Forgot to mention that since v84, Xposed has been complaining about one module embedding the Xposed bridge jar:

05-07 09:24:31.128 I/Xposed  ( 1843): Loading modules from /data/app/daylemk.xposed.xbridge-1/base.apk
05-07 09:24:31.155 W/Xposed  ( 1843):   The Xposed API classes are compiled into the module's APK.
05-07 09:24:31.155 W/Xposed  ( 1843):   This may cause strange issues and must be fixed by the module developer.
05-07 09:24:31.155 W/Xposed  ( 1843):   For details, see: http://api.xposed.info/using.html
05-07 09:24:31.172 I/Xposed  ( 1843):   Loading class daylemk.xposed.xbridge.XposedInit
05-07 09:24:31.176 I/Xposed  ( 1843): DayL[XposedInit]init zygote
05-07 09:24:31.176 I/Xposed  ( 1843): DayL[XposedInit]the package name: daylemk.xposed.xbridge
05-07 09:24:31.176 I/Xposed  ( 1843): DayL[XposedInit]module path: /data/app/daylemk.xposed.xbridge-1/base.apk

Could that cause these issues?

**Comment by rovo89** [comment]
I think I have found and fixed the root cause. The fix will be in v85 once it's released. I'll try to fix a few more things before releasing it though.

You can see the details in the commit message, but in short, it was a low-level issue in the part of Xposed which works around SELinux. It could be triggered if multiple files are supposed to be read at the same time, either by one or multiple modules. XHFW3 was just more likely to trigger this than other modules because it reads four files.

@shooash FYI. Also, please make sure to follow http://api.xposed.info/using.html, i.e. don't use `compile` in the Gradle settings for the Xposed jar. For some reason, the classes didn't end up in your APK, but that might just be luck.

**Comment by rovo89** [comment]
> Forgot to mention that since v84, Xposed has been complaining about one module embedding the Xposed bridge jar

It shouldn't cause these issues, but it might cause others see (rovo89/XposedBridge#97). If nobody has informed the module developer yet, please do so.

**Comment by F-i-f** [comment]
@rovo89 Thanks for the fix.  I'll be reopening the issue if the bug still manifests itself with v85.
I've also opened the issue https://github.com/lj3lj3/XBridge/issues/2 regarding the miscompiled module.

**Comment by shooash** [comment]
@rovo89 Thanks a lot! Can't wait to try if the bootloop issue gets completely fixed (meanwhile I found some problems that seemed to be related to bootloops on my side).  As for the compile rules I know xposed jar should not be compiled and it is not on PC builds. But when testing on AIDE I have to use "compile" and have only sources jar in that folder - it's a workaround cause the AIDE doesn't understand "provided" tag. Thanks!
