### ISSUE TITLE
Intel Z8300 (Cherry Trail) Support

### ISSUE THREAD

**Issue by errmalt** [rovo89/Xposed#173]
Xposed doesn't seem to work on tablets with this processor running Android 5.1.

**Comment by rovo89** [comment]
https://github.com/rovo89/XposedBridge/wiki/Bugs#which-information-should-i-include-in-a-bug-report

**Comment by lblabr** [comment]
some thing to me, i have:

CHUWI Hi10
Proceesor: Intel Z8300

after installing ..x86..zip with TWRP i get an bootloop

some help would be great ;-)

**Comment by RenjarP7** [comment]
Read the article, rovo posted the link above you

**Comment by lblabr** [comment]
sorry i#m not that expert, but i will provide additional information ... i have read that there are common problems with Z8300 processor... can somebody confirm or provide a link with more informations ?

**Comment by lblabr** [comment]
Device: CHUWI HI10, 

ROM: Stock ROM, with root, 

Build-Nummer: cht_cr_mrd_w-userdebug 5.1 LMY47I eng.softteam.20160509.094222 release-keys ???

Xposed version: Xposed installer 3.0 alpha4
tried to install: xposed-v86-sdk22-x86.zip   

Detailed description of the issue (including exact error messages if applicable)

after installing xposed-v86-sdk22-x86.zip   with TWRP and rebbot i  get an bootloop


Things you have already tried to resolve it
are there things that i can provide ? I tried already the tips from chuwi 8, without succes, but i´m not sure that all steps i done were correct

Steps to reproduce
Chuwi rootet install XPosed Framework

Logs
Can´t be done, to unbrick device new Android has to be flashed

**Comment by lblabr** [comment]
Android Version: 5.1

**Comment by rovo89** [comment]
Sorry, but without logs, I can't help. The document describes several ways to get a log. Using a logcat app is probably not going to work in your case, but at least one of the other options should work.

**Comment by mmm286** [comment]
I have same problem with Chuwi hi8 pro

**Comment by rovo89** [comment]
`Unable to use '/system/framework/x86/boot.oat' because Invalid oat magic for '/system/framework/boot.oat'`
Could you please upload the `/systems/framework` folder? Looks like the vendor has made changes that are incompatible with AOSP.

**Comment by mmm286** [comment]
Hi again.
I attach you my logcat and /systems/framework folder.
Many thanks for your help!

[logcat.txt](https://github.com/rovo89/Xposed/files/460505/logcat.txt)

**Comment by mmm286** [comment]
Sorry I cant upload rar file of system/framework. Is about 30MB, where I can upload to you?
Thanks

**Comment by mmm286** [comment]
Hi again,
I upload framework to mega link:
https://mega.nz/#F!iZtlxB4a!KAaMMO3DGooejXd9tMJi9A

**Comment by lblabr** [comment]
where is the best place to store the files for you ?

**Comment by rovo89** [comment]
Mega is fine, however I was on vacation.
I checked the files and it turned out it's the same issue already mentioned in #77.
So in short, I don't think I'll ever support this.

**Comment by rovo89** [comment]
Just to add: This isn't (necessarily) an issue with this processor, a custom ROM might be closer to AOSP and could therefore be supported by Xposed.

**Comment by Spider84** [comment]
I have same Issue on Sofia 3gr board from Chines CAR Navigation system.
`Invalid oat magic for '/system/framework/x86/boot.oat'`

**Comment by rovo89** [comment]
@Spider84 Then I assume my answers above apply to your device/ROM as well.

**Comment by GitHubTpac** [comment]
Hi Rovo89! welcome back from your vacation. I hope you enjoyed.
Straight to the point: Mipad2 14nm intel atom X5-z8500 Android version 5.1 AOSP DualOS-booting windows 10. or only one of them.

The AOSP is some how a supported version from Xiaomi that I installed. Pure aosp and not a MIUI version.

This is the whole folder 85MB from my google drive https://drive.google.com/open?id=0B7dqzR1J--1NWlBPT0VMRzRiQW8


is is not the same issue #77 I think. Unfortunately Intel has dropped the manufacturing of phones and tablet because it wasn't enough profitable.

The good news it that I you could "hack" the "oat" on these, then you could do it on future Intel drones too... Because they are investing on drones-cpus that are much more powerful and power-demanding.

Also, there will be a bounty... I will test yours and report bugs for you... I have tested zips from SolarWares with bootloops... I got them from here: http://forum.xda-developers.com/showpost.php?p=67242362&postcount=36

I will hold my thumbs and wish you the best Rovo89

**Comment by GitHubTpac** [comment]
testing post-function after closed

**Comment by GitHubTpac** [comment]
What is wrong with you rovo89? You have the knowledge most of us all about xposed. 

Did you stumble on this big hack? Is this Cherry Trail a hardware issue for you or is it because the executive core software hardware-customized and is unknown for you and thereby you can't give the x86_64 a try??

Do you know other good people that you recommend, who's have the knowledge to exploit this famous hack on z8500!

come on, give it a try if you have some time. I thought it was I challenging problem that you want to overcome on.

Come on Rovo89! Just do it!  I'll send my device for you and all the necessary file with some donations.
You deserve all those bounties. So, What do you say?  Are you in? Or chickening?

Sincerely, one of your admires
Tpac Shakur aka Elvis Presley  

One love

**Comment by Miroku77** [comment]
Got it working flawlessly with AMIDUOS-XPOSED =)))

https://forum.xda-developers.com/x98-air/general/xposed-teclast-x98-plus-ii-t3571839#post71743254

**Comment by GitHubTpac** [comment]
Thank you Miroku77, I will check after it, thank you! Thank you!
I have DualOS 64GB AndroisAOSP + Windows10 on MiPad2.   I have to make a backup and then flash form scratch and report back!   My problem is that TWRP don't work when dualOS, therefore I have to delete everything I worked with (after backup) and coming back to this thread and report back!  This is very good news and I will inform to everybody else after a successful boot with framework working. 

Next thing after that is to hope other modules will work too.

Thank you for telling me and thankyou "Wheel"-xda!

Thank you also Rovo89!  Love

**Comment by brainvision** [comment]
hi guys, I know about amiduos porting but unfortunately:

**1. it's only API22
2. it's pretty old framework version (v81)**

now I'm using a Lineage OS 13 so it would not work anymore. But now that we know it's possible to build the framework for x86_64 why not try? Here and on xda it's full of peope willing to test everithyng you would pass them :D
