### ISSUE TITLE
How do Xposed logging affect performance?

### ISSUE THREAD

**Issue by aviraxp** [rovo89/Xposed#209]
There have been rumors universally since about one or two years ago that Xposed will largely affect performance because it will write lots of logs into disk, which bring unnecessary I/O and memory occupation, especially some modules like to record lots of logs. They recommend create a blank error.log and limit its permission to prevent logs from recording.

I am really doubt about that. Though I am not good at C++, but from what I read in the log part I do not see anything that will largely affect performance. So would you like to clarify about that?

Thank you, and Happy New Year.

**Comment by rovo89** [comment]
As you already say... why should it affect performance? The logs are written to logcat first (same CPU/memory usage as any other standard Android logging, no disk usage), and are then written to file via Xposed's logcat wrapper.

It obviously depends on how much is being logged. Xposed itself writes like 50 lines during boot, depending on how many modules you have. **That's all, and that definitely doesn't impact performance.**

Yes, if you have a module that writes hundreds of log lines every second (either intentionally or because it keeps crashing), that might impact performance. But you probably don't want to use such a module anyway. In the [API docs](http://api.xposed.info/reference/de/robv/android/xposed/XposedBridge.html#log(java.lang.String)), I warn about flooding the logs with debug stuff - it's an *error* log. Modules can simply use `Log.d()` etc. for debug messages, or should at least have a switch for them.

And even if a module goes wild, the log file is limited to 5 MB. So the hack you described is total non-sense.

**Comment by aviraxp** [comment]
Yep, I agree with you, the logs are collected through ring buffer in memory if I remember it correctly. The fact is many developers uses xposed log to log some debug stuff because almost all users don't know how to take logcat and can only export xposed log, but the impact is limited. Anyway, thanks!
