### ISSUE TITLE
File safemode_disable should still exists, control Xposedusing "on" "off"

### ISSUE THREAD

**Issue by pylerSM** [rovo89/Xposed#23]
Fle safemode_disables hould still exists and "on" or "off" should be written there. For users with bootloop it easier to send echo "off" > safemode_disable then creating new file.

**Comment by rovo89** [comment]
I know you just want to help and contribute, but the way you're doing it is often counter-productive (and therefore a bit annoying) for me.

There are still big tasks to solve until we can call Xposed for Lollipop "stable". I rarely even have time for that. Still, I try to read the suggestions and bug reports posted here and reply to them, which obviously takes time away from development/fixing/research.

The title and the description of this issue is full of typos, making it look like you just dropped it here in a haste. If these two/three sentences look so careless - what do you think my impression is about the time you spent evaluating this idea? I expect people to think about pros and cons beforehand and explain their thoughts here. I expect that they consider that Xposed has hundreds of thousands of users, if not millions. A change that might be useful for a few people might confuse many others. A little change for one edge case might have a big impact on lots of other situations. Every new feature and increase of complexity/variants has the potential to increase the time required to maintain the codebase and support users, it's not like "add those 20 lines and then forget about them". Therefore, everything should be as clean as possible, despite the fact that the general idea of Xposed is kind of "hacky" by definition.

In other words: Contributions (with or without code) are very welcome, but they should fit to the project in terms of quality, scalability and carefulness. Otherwise, they're taking the focus away from the important stuff.


Having a closer look at this particular suggestion, I feel confirmed in my initial impression. Nobody would need to create the `safemode_disable` file if they're in a bootloop - because it won't change anything about the bootloop. It just disables the volume button trigger for Xposed safemode. So if you're paranoid and rely on Xposed being active to protect your device's security, you can prevent an attacker from disabling Xposed during boot. The file you probably mean is simply called `disabled` in the `conf` folder. It wouldn't have been too hard to find this out.

Now we could discuss whether it's clear what "on" and "off" mean in this context: "disabled = off" is a double negative, so to me it would mean that Xposed is actually enabled. Anyway, I'm wondering whether this would really be easier. The same `echo "something" > conf/disabled` command would also create the file if it doesn't exist. Where's the benefit?

Taking two steps back, I have already thought about getting rid of that file completely and checking a persistent system property instead. This could be done earlier, as it doesn't require the services to work around SELinux restrictions. Users could execute something like "setprop persist.xposed.enabled 0" to disable Xposed without uninstalling it. That's something to think about, but with rather low priority. In Lollipop, most problems will be with the modified ART runtime, and neither the file nor the property would be able to prevent that.
