### ISSUE TITLE
xposed v88.1 on Note8 7.1.1 battery drain

### ISSUE THREAD

**Issue by suirzes** [rovo89/Xposed#259]
Samsung galaxy SM-N950F, running 7.1.1, N950FXXU1AQI1_N950FOXM1AQHF_SEB

No problems encountered after installating: twrp 3.1.1 + either magisk v14 or magisk v14.2

Phone starts heating and battery draining when doing NEXT steps:
1. just flashing xposed-v88.1-sdk25-arm64, without installing XposedInstaller_3.1.2 apk.
2. flashing xposed-v88.1-sdk25-arm64 and then installing XposedInstaller_3.1.2 apk.
3. It also starts heating up/draining batt when flashing xposed-v88.1-sdk25-arm64 on top of already installed XposedInstaller_3.1.2 apk
4. drain starts after performing either framework installation methods - flash and installer install.

5. it heats extremely only when being used. if i leave it alone, it cools down after some 10 mins. when unlocked, it starts heating up once again.

I attach couple of catlogs i managed to capture during heatup.

[2017-10-14-14-53-26.txt](https://github.com/rovo89/Xposed/files/1384671/2017-10-14-14-53-26.txt)
[2017-10-14-14-46-46.txt](https://github.com/rovo89/Xposed/files/1384672/2017-10-14-14-46-46.txt)

Wakelog shows no app is acting out of order.

**Comment by raaomoka** [comment]
Having similar issue on my 256GB Exynos Note 8 SM-N950N here in Canada. Although, it doesn't heat up, the battery drains rapidly with XPosed framework installed. Like in just 30 minutes with no use, battery had gone down to 88%. Whereas without XPosed installed, battery is still at 94% after almost 2 hours off the charger and ~35 minutes of use.

Any suggestions for a fix? Really want XPosed mainly to gain access to XPrivacy.

**Comment by rovo89** [comment]
Did you give it a bit of time? The two logs are taken during/shortly after the first boot. The system needs to compile additional information for .odex files at that time, which of course requires CPU time and therefore battery. This is only done for system apps, it will be done in the background for user apps. That means two things: a) user apps will be interpreted/JITted, which takes again more CPU than usual, and b) user apps will be compiled when the phone is idle, which also takes a lot of CPU. I think b) only happens while the phone is charging, but not sure.

Anyway, please try to give it some time. System apps are handled during first boot, user apps willl be fine after b) has been done for all apps.

Additionally, we have https://github.com/rovo89/XposedBridge/issues/205 here, which might also add CPU load.

**Comment by suirzes** [comment]
Ok. Will give it couple of days on the Magisk 14.3

**Comment by raaomoka** [comment]
Hi rovo89,

Approximately how long do you think it'll take to go through all the initialization? I have ~200 apps installed via Smart Switch, the rest is all system apps.

Thanks in advance.

**Comment by suirzes** [comment]
Ok, as you said, i gave it a little time, did everything in steps, gave system some time in between to recompile everything and did some logging after/before each step.

First log comes with only twrp and magisk 14.3 installed. no xposed. no heating. no battery drain.
[2017-10-17-17-03-12-no1-noXpf.txt](https://github.com/rovo89/Xposed/files/1395655/2017-10-17-17-03-12-no1-noXpf.txt)
Second and third logs come 7-14hrs after flashing normal 88.1 xposed. heating noticeable and fast to manifest itself while using phone. in standby it cools down. serious battery drain, instead 1charge/day, 2-3 charges ar needed.
[2017-10-18-00-39-38-no2-7hrsAfterXposed.txt](https://github.com/rovo89/Xposed/files/1395656/2017-10-18-00-39-38-no2-7hrsAfterXposed.txt) and [2017-10-18-07-47-13-no3-14hrsAfterXpf.txt](https://github.com/rovo89/Xposed/files/1395657/2017-10-18-07-47-13-no3-14hrsAfterXpf.txt)
Sixth log comes after installing Android Xposed app in system. no noticeable difference from 2nd and 3rd logs.
[2017-10-18-17-15-19-no6-7hrsAfterXpsdAppInstall.txt](https://github.com/rovo89/Xposed/files/1395660/2017-10-18-17-15-19-no6-7hrsAfterXpsdAppInstall.txt)
Seventh log - some time after 2 xposed modules (xglyph and xinsta) were installed. battery drain increased.
[2017-10-18-18-07-39-no7-modulesInstalled.txt](https://github.com/rovo89/Xposed/files/1395661/2017-10-18-18-07-39-no7-modulesInstalled.txt)
And final log - xposed disabled via interface in app. not much difference noticed in battery drain compared to 7th log.
[2017-10-18-19-50-23-no8-XpsDisabledViaInterface.txt](https://github.com/rovo89/Xposed/files/1395662/2017-10-18-19-50-23-no8-XpsDisabledViaInterface.txt)

Hope it helps. I had xposed on 4.4.4, had absolutely no issues with battery. But then there were no fancy odex etc...

**Comment by pressRtowin** [comment]
why was this closed?

**Comment by suirzes** [comment]
Yhe solution was found and will be implemented in v88.2. At the moment rovo89 offered a test version on his next edition. You can find it in https://github.com/rovo89/XposedBridge/issues/205 . It helped me.

If it wount help you, ill reopen the thread

**Comment by raaomoka** [comment]
Yeah, why exactly was this closed? Even after 3 days of waiting, XPosed framework v88.1 was still 'causing serious issues on my Exynos Note 8, including this issue of the battery draining rapidly with barely any use (albeit no overheating):

![xposed causing high battery usage in android system](https://user-images.githubusercontent.com/2476232/31996793-0547e0f2-b947-11e7-8b61-0eae3921a9e9.jpg)

Plus the following issues:

- My Note 8 began randomly lagging like crazy, the keyboard input was so slow, the system UI would randomly crash and show the lockscreen after a minute of going blank, etc. At first, I thought it was XPrivacy that was 'causing the issue due to some permission I had restricted, but even with that disabled, the issue still persisted.

- Bixby voice kept crashing over and over again, without me even invoking it, and couldn't even open Bixby home.

- Not sure if completely related, but the Amazon Shopping and Amazon Store app began crashing over and over again on every launch, whereas during initial setup, I seamlessly used the Amazon App Store app to install several app updates to apps I had transferred from my OnePlus One via Smart Switch. Uninstalling and re-installing had no effect, so, definitely had nothing to do with the app being outdated. However, maybe it was due to an outdate Android System WebView instead of just XPosed, but then how did they function during initial setup? Not entirely sure...

- etc.

Still on the look out for newer versions of XPosed, hopefully with all of he above issues addressed and working flawlessly with Magisk. But in the mean time, I've uninstalled the XPosed framework and the difference is like night and day. None of the above issues, and after a day at work with light use, still have the following left:

![after a day at work with light use](https://user-images.githubusercontent.com/2476232/31997037-ce66acac-b947-11e7-9d25-86954e42481f.jpg)

Heck, was even able to easily make it through 2 full work days on a single charge without XPosed framework:

![easily make it through 2 work days](https://user-images.githubusercontent.com/2476232/31997046-d6757310-b947-11e7-9ad5-e12441830eda.jpg)

Whereas with the current non-systemless XPosed framework, even with the same light use, would have to recharge in the middle of the day.

**Comment by suirzes** [comment]
@rovo89 it appears that after some time a new error develops. It reoccured twice, after couple of days with xposed. both v88.1 and v88.2beta.
[screenshot_20171026-083954](https://user-images.githubusercontent.com/32795781/32036865-169be436-ba2b-11e7-97a6-005326a56cda.jpg)
[2017-10-26-08-49-29-new-drain.txt](https://github.com/rovo89/Xposed/files/1417083/2017-10-26-08-49-29-new-drain.txt)

**Comment by raaomoka** [comment]
@suirzes Almost got excited after reading your first post until I read your second one. Oh well, still gonna try this XPosed v88.2beta to see if there's noticeable improvement on my end. 'Cause, on top of this issue of the battery draining rapidly with barely any use (albeit no overheating):

![image](https://user-images.githubusercontent.com/2476232/32071067-5c2b1f7e-ba4b-11e7-9c09-6996ee215888.png)

even after 3 days of waiting, XPosed framework v88.1 was still 'causing the following serious issues on my Exynos Note 8:

- My Note 8 began randomly lagging like crazy, the keyboard input was so slow, the system UI would randomly crash and show the lockscreen after a minute of going blank, etc. At first, I thought it was XPrivacy that was 'causing the issue due to some permission I had restricted, but even with that disabled, the issue still persisted.

- Bixby voice kept crashing over and over again, without me even invoking it, and couldn't even open Bixby home.

- Not sure if completely related, but the Amazon Shopping and Amazon Store app began crashing over and over again on every launch, whereas during initial setup, I seamlessly used the Amazon App Store app to install several app updates to apps I had transferred from my OnePlus One via Smart Switch. Uninstalling and re-installing had no effect, so, definitely had nothing to do with the app being outdated. However, maybe it was due to an outdate Android System WebView instead of just XPosed, but then how did they function during initial setup? Not entirely sure...

- etc.

Uninstalled the XPosed v88.1 framework and the difference was like night and day. None of the above issues, and after a day at work with light use, still have the following left:

![after a day at work with light use](https://user-images.githubusercontent.com/2476232/32071183-bc6ab156-ba4b-11e7-8bee-b7df2cd68ceb.jpg)

Heck, was even able to easily make it through 2 full work days on a single charge without XPosed framework:

![easily make it through 2 work days](https://user-images.githubusercontent.com/2476232/31997046-d6757310-b947-11e7-9ad5-e12441830eda.jpg)

Whereas with the non-systemless XPosed framework v88.1, even with the same light use, would have to recharge in the middle of the day. Would soon post my experience with this v88.2beta.

BTW, how are you getting the logs on your Note 8? I should probably be doing the same if and when I experience any of the above issues.

**Comment by suirzes** [comment]
@rovo89 Update for the latest logs. It lasted for about... 2hrs, then it stopped. mystery to me. could it be sync related?

@raaomoka one tip - when posting pictures, delete an exclamation mark before the links - it will show the link instead of the whole picture. :)
You can catch system logs using an application - catlog. it's free and simple to use.

**Comment by rovo89** [comment]
Please try v88.2.

**Comment by raaomoka** [comment]
Thank you very much rovo89! After just a few minutes of having installed, I can already say that the battery life performances with XPosed v88.2 is far better than what I was getting with XPosed v88.1.

Will give it a few days and report how it performs after that. But so far, so good :grin:

**Comment by raaomoka** [comment]
Hey @rovo89,

So, after going through a full day with XPosed framework v88.2 on my Note 8, SM-N950N, it appears that battery life has still gone down. I get about 2 hours less worth of screen on time compared to without XPosed. However, it's still significantly better than v88.1 and I can still easily make it through the day:

[With XPosed Framework v8.2 and Installer v3.1.4](https://user-images.githubusercontent.com/2476232/32280908-e8fa0ff0-bee2-11e7-9575-56f43b5b838c.jpg)

[With XPosed Framework v8.2 and Installer v3.1.4 (Screen on Time)](https://user-images.githubusercontent.com/2476232/32280964-0cc38a2e-bee3-11e7-90cb-5328b54773cc.jpg)

Plus, not experiencing any of the other issues stated above 😁 Thanks again for your time and effort in making this versatile tweak for Android 👍
