### ISSUE TITLE
Suggestions for Xposed

### ISSUE THREAD

**Issue by stuffdude99** [rovo89/Xposed#26]
Hello rovo89,
I hope this is the right place to send in suggestions. I love xposed framework and I'm planning on donating soon. I just have few suggestions:
•I know that xda can be used for commenting, but it would be amazing if it was incorporated in xposed
•Using Accounts from google and XDA would make the commenting community bigger. 
•Statistics will let you know your users and will help you grow. 
Those were some suggestions I have for xposed framework. I hope you liked it :D

P.S. - I am not a professional programmer, I just started learning java. 
Regards,
Stuffdude99

**Comment by wbedard** [comment]
Hey Stuffdude99,

I think I understand what you have in mind! However, I am certain that you are suggesting it to the wrong developer. Rovo develops the XPosed framework, and only when he can find the spare time. 

What you are suggesting is something for a developer who works on more "user-facing" aspects of XPosed, such as modules. While your idea could be implemented as a XPosed module, it would be a pretty bad use of the XPosed framework.  Your idea would be better implemented as an Android app or even just a website, such as what XDA already has. 

So, while rovo is absolutely the wrong person to make your request to, the XDA Forums do have a lot of other developers who work on apps (more) and websites (less) where your suggestion would be better received. Good luck! 

R/
wbedard

**Comment by rovo89** [comment]
> I hope this is the right place to send in suggestions.

Well, not really. For the GUI (instead of the framework), https://github.com/rovo89/XposedInstaller would be a better place. Hence, I will close this issue here to get it off the "open" list. Feel free to reply anyway.

Anyway, it's not quite clear to me what you mean with "commenting". You mean general feedback and discussions on modules? I'm afraid that I don't want that integrated. Obviously, it's a lot of work to build something like this, both in initial and maintenance efforts. It will need a server to manage all the comments and accounts. It needs moderators, as people can become very rude. I think XDA is a much better place for this. Plus, comments like in Play Store don't really help to improve, it's mostly a one-way channel and hardly anyone will provide logs.

Statistics go into the same direction. We do have download statistics, and I plan to add a chart or so some time in the future. Sure, it would also be interesting how many peope are actually using a module or the framework. But again, this would require people to register accounts or at least make the app send data to a server regularly. Apart from the server load with 100,000s or maybe even millions of users, this could easily raise privacy concerns.
