### ISSUE TITLE
AppCrash and AppFreeze

### ISSUE THREAD

**Issue by aries2747** [rovo89/Xposed#262]
The Problem occurs in 2 of my apps, the PhotoTan App (Commerzbank) loads infidently and the Banking App (Commerzbank) crashes immediatly when i try to open it.

The errors only occur when Xposed is installed (Lineage 14.1 hiaeuhl, Htc One A9, Xposed v88 and v88.1 sdk25). As soon as i uninstall xposed everything is working fine.

I have attachet a logfile where i first started the Banking app (Crashed) and then started the PhotoTan app (Freezes or loads infidently)

[banking-xposed.txt](https://github.com/rovo89/Xposed/files/1387819/banking-xposed.txt)

**Comment by wanam** [comment]
`10-16 16:31:18.672 E/AndroidRuntime( 5687): Process: de.commerzbanking.mobil, PID: 5687
10-16 16:31:18.672 E/AndroidRuntime( 5687): com.commerzbank.mobilebanking2.common.exception.CrashAppDoNotCatchThis
10-16 16:31:18.672 E/AndroidRuntime( 5687): 	at com.commerzbank.mobilebanking2.common.util.AndroidUtil.tamper(Unknown Source)`

Your app (like many others) crashes because it does some tampering checks, i don't think this can be handled within xposed framework, and i think trying to hide xposed is a lost race, most of those apps are proguarded, but still this can be done with a module though.

**Comment by aries2747** [comment]
Ok, it was a try, hoped that there was a chance to get it running :-)
