### ISSUE TITLE
Suggestion: Sorting by compatibility

### ISSUE THREAD

**Issue by SyCoREAPER** [rovo89/Xposed#36]
(I am only posting here because I don't know how else to get your attention, apologies if this isn't the correct place)

Setting in User Interface:
Show:
[]Xposed <4.4.4 
[]Xposed 5.0
[]Xposed 5.1
[]Xposed (All) - Default

Example, they fill out something like this that the App would recognize:
Developer Form:

http://i.imgur.com/vJCl7HU.png

I only mention this alternate implementation because I and am sure others don't care about LG, Sony, Amazon, etc.. specific modules and some people would prefer to see only universal usable modules. 
EVEN MORE Work but it could be taken a step further by adding the above in addition to allowing the user to hide device specific modules:

http://i.imgur.com/x0hlFfi.png

http://forum.xda-developers.com/showpost.php?p=60279502&postcount=5739

**Comment by rovo89** [comment]
To make it short:
a) This would be more suitable for the https://github.com/rovo89/XposedInstaller project, that's why I close this issue as "invalid" here.
b) I don't have time for such huge changes at the moment.

A more detailed answer about such "tagging" can be found here: http://forum.xda-developers.com/xposed/tag-organization-t2799339

**Comment by rovo89** [comment]
Note that a reduced version, where developers just specify min/max Android version is less work, but still it's not something that I can implement in the near future.

**Comment by pylerSM** [comment]
Somebody may start working on it (java side, should be easier than coding Xposed framework itself), but firstly you should sum up current situation, whether is worth to work with "art" branch of Xposed Installer or it is not ready and will not be for some time. So people would not waste their on implementation which will be rejected by you because of futher changes or so.
