### ISSUE TITLE
Why Xposed sometimes cannot hook String.equals?

### ISSUE THREAD

**Issue by shuxin** [rovo89/Xposed#52]
I've got a very strange problem. When I hooked the String.equals, I found some hooks had missed.
I can see the call from framework hooked OK, but I cannot see any call from apps.

**Comment by wanam** [comment]
Out of curiosity why would hook this method? you can try to workaround this check by analysing and replacing the surrounding method, hooking such atomic method should lead to performance issues.

**Comment by shuxin** [comment]
I found it.

some of them was replace with 
````
172714: ee20 0300 4300                         |001c: +execute-inline {v3, v4}, [0003] // inline #0003
````
by dexopt and some are not.

**Comment by shuxin** [comment]
So.
Is there any way to hook them?

**Comment by rovo89** [comment]
> Is there any way to hook them?

I don't think so, as String.equals() isn't called in this case. There are more inlines like this:
https://github.com/android/platform_dalvik/blob/kitkat-mr2.2-release/vm/InlineNative.cpp#L717

But as @wanam, none of these methods should be hooked, at least not in a productive module. In the worst case, it will crash (e.g. because the callbacks in Xposed might use them, leading to endless recursion), but in any case performance will suffer. Therefore, I mark this as "wontfix".
