### ISSUE TITLE
Hook all the methods of the classes since the app starts

### ISSUE THREAD

**Issue by xly1208** [rovo89/Xposed#63]
I want to hook all the methods for all the classes since the app starts.So I want to know if there is a way to do that. If we can hook all the methods , we can know how the app runs and each method it uses and the values of the parameters. So is there a way ?

**Comment by rovo89** [comment]
In short: No.

I remember that someone developed something like this a while ago, but I think it was for all methods in a class. Getting the names of all classes isn't possible as far as I know, at least not with "normal" functions. You also have to be careful not to hook important methods like those in the String or Log classes, otherwise you'll end up in infinite loops because Xposed uses those classes during hook handling itself.
