### ISSUE TITLE
Xposed breaks wifi calling LG G4 H81110n

### ISSUE THREAD

**Issue by jamesd1085** [rovo89/Xposed#66]
After framework installation wifi calling fails to connect even before adding modules

**Comment by jamesd1085** [comment]
https://app.box.com/s/qz4jry32qiqktppqnyog1bvtr8gypzw8

https://app.box.com/s/hhpvc0ngrw3nk6qike6yuqatf3zh2exk

Sorry these wouldn't paste in my original report

**Comment by siraltus** [comment]
I'm another user who has this problem, here's some more information. 

This is on a T-Mobile (H811) variant of the LG G4. Running Android 5.1, Xposed v74 arm64 sdk22 installed, no modules installed.

When Xposed is installed, WiFi Calling is stuck on "Enabling" and after 2-3 minutes errors out with "REG99: Unable to Connect." Or, it connects for about 2-3 minutes and then disconnects and is stuck on "Enabling" and then errors out with the REG99 error. Uninstalling Xposed instantly resolves the issue.

Logcat and dmesg: https://www.dropbox.com/s/os2u3am349d7trb/wificalling-xposed-logs.zip?dl=0

**Comment by siraltus** [comment]
People over in the unofficial Xposed for Samsung forum are reporting that Xposed breaks WiFi Calling on devices running Android 5.1.1. This might be related. 

http://forum.xda-developers.com/showpost.php?p=62747570&postcount=2801

WiFi Calling works fine on my Galaxy Note 4 running Android 5.0.1, so this might be a 5.1.x-specific problem. I asked them to post their logs here.

**Comment by rovo89** [comment]
Is this "WiFi Calling" thing a proprietary app by T-Mobile? I have never seen such an option on CM12.1, do you know if this is available on open-source ROMs as well? I'm having a hard time understanding which parts this feature consists of and how it fails.

There's one part in the logs that looks interesting:
```
E/IPPhoneSettings( 6463): java.lang.RuntimeException: Unable to get provider com.movial.ipprovider.IPPhoneProvider: java.lang.ClassNotFoundException: Didn't find class "com.movial.ipprovider.IPPhoneProvider" on path: DexPathList[[zip file "/system/app/ip-provider/ip-provider.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
```

Could this be related or is it an app you have installed? Could you upload the contents of /system/app/ip-provider please?

**Comment by jamesd1085** [comment]
Its tmo custom baked for stock roms from them...and yes the movial.ip is a crucial to wifi callling...also in the last few months tmo added source to aosp for wifi calling

**Comment by siraltus** [comment]
Yes, this is proprietary T-Mobile technology, however, it has also been added as a feature to the Nexus 6 and is available as part of the T-Mobile factory image for the Nexus 6 from Google. I'm not sure if the implementations are the same.

Here's our XDA thread: http://forum.xda-developers.com/tmobile-g4/help/wifi-calling-errors-10n-update-t3191362/page2

We suspect this is some kind of authentication issue because as long as the phone has LTE signal and VoLTE enabled, WiFi Calling stays connected, but as soon as LTE signal is lost (even if the phone drops to HSPA), WiFi Calling disconnects.

Here is /system/app/ip-provider: https://www.dropbox.com/s/l2h0a9x2xeex4m5/ip-provider.zip?dl=0

**Comment by jamesd1085** [comment]
Here is a link to a thread where we tried to troubleshoot and came up with very little...

http://forum.xda-developers.com/tmobile-g4/help/wifi-calling-errors-10n-update-t3191362

**Comment by jamesd1085** [comment]
On a high note xposed functions flawlessy outside of this small issue...great job

**Comment by jamesd1085** [comment]
https://app.box.com/s/r8x6fhiraobkzar55mbjmgx4qwzpe78w

Wificall apk in case you need to look at it as well

**Comment by rovo89** [comment]
Ok, I have tried to recompile the ip-provider odex files and it worked. So at least in my environment, it doesn't seem to be a failing compilation of those files.

I have to admit that I'm in the dark about the root cause for this issue, so I have to collect more information to narrow it down.

First, it would be helpful to see if the issue is caused by Xposed's hooks or by its ART libraries. For that, please create an empty file called `/data/data/de.robv.android.xposed.installer/conf/disabled` and reboot. The log in Xposed Installer should say that Xposed wasn't loaded because of that file. Does WiFi calling work then?

If not, it seems to be an issue with the ART libraries. I still can't exclude that recompiling the ROM went wrong, so it would be helpful if you could clear your Dalvik cache, and then immediately after powering on the device, execute `adb logcat -v time > logcat.txt` to capture the logcat as early as possible. That should show errors/warnings happing when my ART variant recompiles the odex files. Those errors could lead to runtime issues later.

In addition, it might be helpful to look at the "IPPolicy" app, wherever that is located. It seems to write several message about WFC into the log, so maybe it can give some hints about the control flow.

**Comment by jamesd1085** [comment]
https://app.box.com/s/0ag2q1ii92jkmr2mvfbsugoxt7e8wani

Here are all the ip related apks i was able to find in system folders(no IPPolicy that icould find)but my laptop is away for service and i have no eta on a return so hopefully siraltus can get you the logs you need...i do know that checking disable resource hooks in the installer app resolved the issue but obviously broke most if not all modules in use...if you need anything else please let me know and i will do my best to help...im not afraid to play guinea pig on untested fixes either so by all means let me know how to help further

**Comment by siraltus** [comment]
Checking "Disable resource hooks" in Xposed did NOT fix the issue for me. Only uninstalling Xposed completely using the uninstaller would fix it.

Creating the "disabled" file also did not fix the issue.

I just wiped Dalvik cache from TWRP and now the phone is bootlooping, so I need to fix it first, then I'll try getting the logs.

**Comment by rovo89** [comment]
@jamesd1085 Unfortunately, the APK files don't contain code. Could cou please upload the odex files from the arm/arm64 subfolders as well?

**Comment by siraltus** [comment]
Here's what I think is related to IPPolicy: https://www.dropbox.com/s/78uzw0w9luomjvd/IPService.zip?dl=0

I just got the phone booting again, so I'll try to uninstall Xposed using the uninstaller and then grab a logcat right after installing it but before it recompiles all the apps.

**Comment by jamesd1085** [comment]
Uploaded same link though

**Comment by siraltus** [comment]
So adb does not see the phone while it boots, it only becomes visible to adb after it finishes booting and settles and then it's shown as "offline." I have the latest device driver and adb bridge (10.0.32). Is there a way to capture the logcat on boot on the phone itself?

**Comment by rovo89** [comment]
Can you try to upload that file again? It seems to be corrupted.
I have sometime seen logcats captured with Chainfire's LiveBoot. I haven't tried that myself though.

**Comment by siraltus** [comment]
Maybe having the complete system partition will be easier so that we don't have to keep uploading random APKs piece by piece? 

Here's the whole thing: https://www.androidfilehost.com/?fid=24052804347781338

The .img file can be browsed with Ext2Read :http://sourceforge.net/projects/ext2read/

I'll try LiveBoot and report.

**Comment by siraltus** [comment]
Here's the LiveBoot log: https://www.dropbox.com/s/sjpenxgpnxhlwz0/liveboot.log?dl=0

**Comment by jackmac92** [comment]
Also experiencing this problem, would more logs help?

**Comment by rovo89** [comment]
Probably not, I first want to check the files that were provided - but as you can imagine, I'm quite busy now.

**Comment by siraltus** [comment]
When using a deodexed ROM, the issue does not occur. So now we know the problem lies in the way Xposed handles/compiles the LG odex files.

**Comment by rovo89** [comment]
Based on the last comment, could someone please try the latest version 79? Clear the Dalvik cache to force a full recompilation.

**Comment by siraltus** [comment]
Tested on a T-Mobile LG G4, issue is still present.

**Comment by ghagiel** [comment]
Works on T-Mobile LG G4 H811 with 10n firmware and Xposed v79. Thx!

**Comment by siraltus** [comment]
Ghagiel, did you put the phone in airplane mode first? WiFi Calling works
with Xposed as long as the phone receives LTE signal, but breaks as soon as
LTE signal is lost. The true test is to put the phone in airplane mode,
turn on WiFi, and then turn on WiFi Calling. It was still stuck at
"Enabling" in my case, followed by "REG99: Unable to Connect."

**Comment by ghagiel** [comment]
For me, it never would work without an LTE signal initially then moving over to just wifi. Had that on stock unrooted brand new phone. Never could get it to work when had no signal then just enabling wifi (just complained about being in airplane mode). I remember reading somewhere that the G4 needs a cell signal initially then hands the rest off to wifi (cuz that makes sense).

When I flashed xposed before v79, wifi calling wouldn't even turn on. Would stay grayed out and had the enabling message forever. Occasionally showed that REG99 error.

With v79 it's back to the way it was. Wifi calling turns on fine, and icon turns green when on a wifi call. I did completely wipe and resetup my phone (unrelated problems), so maybe that has something to do with it?

**Comment by siraltus** [comment]
Ghagiel, since WiFi Calling was broken on a completely stock, unrooted
phone, your problem has nothing to do with Xposed.

This issue is specifically about WiFi Calling breaking AFTER installing
Xposed.

And no, the G4 doesn't need LTE to use WiFi Calling, that's why I asked you
to do the airplane mode test. It's supposed to work in Airplane Mode.

**Comment by ghagiel** [comment]
Admittedly I may be an idiot and have no idea what I am talking about. All I know is as long as I initially have a cell signal, I can turn on wifi calling them leave tmobile coverage (basement) and make calls over wifi. And that this was the same behavior I experienced before xposed completely broke it when installed.

Other people with more knowledge than me should prolly continue testing. One report either way is hardly indicative, after all. I shall update and supply logs is anything changes.

**Comment by rovo89** [comment]
Can you please check if v83 fixes this?

**Comment by jamesd1085** [comment]
Since g4 was updated to 6.0 and T-Mobile version is deodexed problem is gone...I can't speak for those who haven't/won't update but I won't be going back to see...its fine after update though

**Comment by siraltus** [comment]
Disregard jamesd1085's comment. The stock T-Mobile H811 20i ROM is NOT deodexed from the factory. All versions of Xposed prior to v84 will cause this problem.

**Comment by siraltus** [comment]
Xposed version v84 resolves this issue. Tested and confirmed on T-Mobile LG-H811 with 20i software (Android Marshmallow) stock odexed ROM.

**Comment by jamesd1085** [comment]
It must be a module issue on your end...I flashed xposed as soon as we had root on 20i and used WiFi calling without issue...also worked in airplane mode...this was the consensus among others as well...but glad it fixed your issue
