### ISSUE TITLE
Xposed v75: Error -2147483646 while adding app service user.xposed.app

### ISSUE THREAD

**Issue by fda77** [rovo89/Xposed#73]
With v75 I noticed again this error on a Nexus 7 Android 5.1.1. With earlier version i did not noticed it for a long time. Reboot "fixes" it.

```
10-11 18:12:16.865 I/Xposed  (27351): -----------------
10-11 18:12:16.865 I/Xposed  (27351): Starting Xposed version 75, compiled for SDK 22
10-11 18:12:16.865 I/Xposed  (27351): Device: Nexus 7 (asus), Android version 5.1.1 (SDK 22)
10-11 18:12:16.865 I/Xposed  (27351): ROM: LMY48M
10-11 18:12:16.865 I/Xposed  (27351): Build fingerprint: google/razor/flo:5.1.1/LMY48M/2167285:user/release-keys
10-11 18:12:16.865 I/Xposed  (27351): Platform: armeabi-v7a, 32-bit binary, system server: yes
10-11 18:12:16.865 I/Xposed  (27351): SELinux enabled: yes, enforcing: yes
10-11 18:12:16.870 E/Xposed  (27405): Error -2147483646 while adding app service user.xposed.app
10-11 18:12:21.868 E/Xposed  (27351): Zygote service is not running, Xposed cannot work without it
```

**Comment by rovo89** [comment]
Has this ever happened to you since then? This seems to be a very rare issue. The code for adding the service is pretty much unchanged since the first version for Lollipop, so probably it wasn't caused by a change in Xposed, but by unfortunate, rare circumstances (I assume during a soft reboot?). As this would be extremely hard to debug if it's not reproducable, I think I won't be spending time on it, ok?

**Comment by fda77** [comment]
I use most time soft-reboot during developing modules. It occurs maybe in 1 of 20 reboots. So as noone other notices it, it's okay :D
