### ISSUE TITLE
Issue in InnJoo One 3G HD Lollipop 5.1

### ISSUE THREAD

**Issue by adil06** [rovo89/Xposed#81]
HELP I am using InnJoo One 3g hd Lollipop device with custom recovery TWRP. I install the .zip file (xposed-v75-sdk22-arm.zip) after installation I reboot my device then it starts optimizing apps and restarts frequently and again optimize the apps only optimizing screen and restart for several hours.

Then I install the xposed from recovery by using .zip file (xposed-uninstaller-20150831-ar...) and again it optimize the apps but this optimization finish in 5-10 mins.

Please HELP I am unable to install and use xposed on my device. Thanks in advance.

**Comment by adil06** [comment]
Help required please

**Comment by liudongmiao** [comment]
You should provide more information, for example, logs.. without log, it's hard to do anything.

**Comment by adil06** [comment]
How could I give the log because after installation phone only reboot several times but does not come main screen.

**Comment by adil06** [comment]
Please guide me I will provide it too. Thanks in advance.

**Comment by adil06** [comment]
I have collected the log file. Please tell me your email address it is very long

**Comment by adil06** [comment]
Log Collector version: 1.2.0
 Device model: ONE 3G HD
 Firmware version: 5.1
 Kernel version: 3.10.72+
wind-kernel@droid )
#1 SMP PREEMPT Sun Sep 6 15:59:41 CST 2015
 Build number: ONE 3G HD-Android5.1-InnJoo-20150906-V1

--------- beginning of main
11-10 22:37:11.341 D/FeatureProxyBase( 8502): FeatureProxyBase class constructor
11-10 22:37:11.341 D/FeatureProxyBase( 8502): getService(), serviceName = multiwindow_service_v1
11-10 22:37:11.342 D/FeatureProxyBase( 8502): FeatureProxyBase class constructor
11-10 22:37:11.342 D/FeatureProxyBase( 8502): getService(), serviceName = multiwindow_service_v1
11-10 22:37:11.348 D/ProgressBar( 8502): setMax, old = 100, new = 10000, backtrace = android.widget.ProgressBar.<init>:300 android.widget.ProgressBar.<init>:262 android.widget.ProgressBar.<init>:258 java.lang.reflect.Constructor.newInstance:-2 java.lang.reflect.Constructor.newInstance:288 , this = android.widget.ProgressBar{19477805 V.ED.... ........ 0,0-0,0 #102000d android:id/progress}
11-10 22:37:11.348 D/ProgressBar( 8502): setProgress, old = 0, new = 0, max = 10000, backtrace = android.widget.ProgressBar.setProgress:1311 android.widget.ProgressBar.<init>:302 android.widget.ProgressBar.<init>:262 android.widget.ProgressBar.<init>:258 java.lang.reflect.Constructor.newInstance:-2 , this = android.widget.ProgressBar{19477805 V.ED.... ......ID 0,0-0,0 #102000d android:id/progress}
11-10 22:37:11.349 D/ProgressBar( 8502): setSecondaryProgress, old = 0, new = 0, max = 10000, backtrace = android.widget.ProgressBar.<init>:304 android.widget.ProgressBar.<init>:262 android.widget.ProgressBar.<init>:258 java.lang.reflect.Constructor.newInstance:-2 java.lang.reflect.Constructor.newInstance:288 , this = android.widget.ProgressBar{19477805 V.ED.... ......ID 0,0-0,0 #102000d android:id/progress}
11-10 22:37:11.374 D/ViewRootImpl( 8502): disable hardware acceleration by APP!!!, this = ViewRoot{3e755ce5 com.xtralogic.android.logcollector/com.xtralogic.android.logcollector.SendLogActivity,ident = 2}
11-10 22:37:11.381 D/Dialog  ( 8502): show
11-10 22:37:11.381 D/Surface ( 8502): Surface::disconnect(this=0xb459f700,api=2)
11-10 22:37:11.381 D/GraphicBuffer( 8502): unregister, handle(0xb44f0ac0) (w:720 h:563 s:720 f:0x1 u:0x000933)
11-10 22:37:11.383 D/GraphicBuffer( 8502): unregister, handle(0xb44f0c40) (w:720 h:563 s:720 f:0x1 u:0x000933)
11-10 22:37:11.386 D/GraphicBuffer( 8502): unregister, handle(0xb44f0ca0) (w:720 h:563 s:720 f:0x1 u:0x000933)
11-10 22:37:11.405 D/Dialog  ( 8502): dismissDialog
11-10 22:37:11.441 D/Surface ( 8502): Surface::connect(this=0xb459f700,api=2)
11-10 22:37:11.443 D/GraphicBuffer( 8502): register, handle(0xb44f0e80) (w:563 h:230 s:576 f:0x1 u:0x000933)

**Comment by adil06** [comment]
I will send the log file after installing xposed tomorrow using adb

**Comment by rovo89** [comment]
The log you posted is indeed useless, it's way to short... using "adb logcat -d -v time > logcat.txt" is what I usually recommend. You can upload the result to pastebin or something like that and then just post the link here.

**Comment by adil06** [comment]
Log is required after installing xposed or before by the I will post the both thanks rovo89.

**Comment by rovo89** [comment]
After installing, while it's in the bootloop. I need to know the exact reason of the crash to say anything more about it.

**Comment by adil06** [comment]
Dear Rovo89, please see the below Logcat file link using command "adb logcat -d -v time>logcat.txt" after installing [xposed-v75-sdk22-arm.zip]

http://pastebin.com/vkM7Vp0c

Please also see the video of the issue which I am talking

http://www.dailymotion.com/video/x3dgqd9

Any further information required please ask, I will share as soon as possible.

Thanks in advance.

**Comment by rovo89** [comment]
Sorry, the logcat seems to be cut off... Can you please try again, but this time execute "adb logcat -v time > logcat.txt" (no "-d"), then wait for a few minutes (at least 1-2 restarts) and then press Ctrl+C? Then please upload the new log. Thanks.

**Comment by adil06** [comment]
Dear Rovo89, on pastebin there is 500 KB limit. Please see the attachment as the adb command does not start immediately because my pc is detecting the device after few seconds of mobile restart (means after company logo) and starts logging hereafter. Hope this time it works for you the logging were running till 2-3 restarts. Thanks in advance Rovo89.

**After Installing (Xposed v78 SDK22 ARM)**
[After Xposed v78 SDK22 ARM.txt](https://github.com/rovo89/Xposed/files/35605/After.Xposed.v78.SDK22.ARM.txt) 3.84 MB


**Before Installing (Xposed v78 SDK22 ARM)**
[Before Xposed v78 SDK22 ARM.txt](https://github.com/rovo89/Xposed/files/35601/Before.Xposed.v78.SDK22.ARM.txt) 13.30 MB

**Comment by adil06** [comment]
Using "adb logcat -v time > logcat.txt"

**Comment by rovo89** [comment]
```
11-16 19:32:05.012 I/ANRManager( 4957): monitor Broadcast ANR process (4957)
11-16 19:32:05.012 I/ANRManager( 4957): setZramTag: 5
11-16 19:32:05.013 D/ANRManager( 4957): preDumpStackTraces Begin tracePath:/data/anr/mtk_traces.txt
11-16 19:32:05.013 D/ANRManager( 4957): preDumpStackTraces Stage I Begin tracePath: /data/anr/mtk_traces.txt
11-16 19:32:05.022 I/ANRManager( 4957): preDumpStackTraces process: 4957 parent: 4671 zygote: [4671]
11-16 19:32:05.022 I/Process ( 4957): Sending signal. PID: 4957 SIG: 16
11-16 19:32:05.023 F/libc    ( 4957): Fatal signal 16 (SIGSTKFLT), code 0 in tid 4957 (system_server)
```

Note that the same error also appears without Xposed, but is handled/ignored there:
```
11-16 19:37:05.023 I/Process (  776): Sending signal. PID: 776 SIG: 16
11-16 19:37:05.023 I/art     (  776): Thread[9,tid=789,WaitingInMainSignalCatcherLoop,Thread*=0xb463c000,peer=0x12c020a0,"Signal Catcher"]: reacting to signal 16
```

SIGSTKFLT indicates low memory, is this a low-end device? If it's not - do you know if others with the same ROM/device also have this error? No matter whether the error is handled or not, it shoudn't occur in the first place.

**Comment by adil06** [comment]
It's 2gb ram with 1.4 ghz octa core processor with 16gb rom. I don't know whether other with same ROM using xposed or not.
Please guide me what should I do.

**Comment by adil06** [comment]
Please see comment # 10 in the below link one person also sticks

http://forum.xda-developers.com/android/development/innjoo-one-3g-hd-5-1-lollipop-root-t3201524

Please guide me I am very desperate to use xposed in my mobile.

**Comment by adil06** [comment]
I now you would be busy in other projects too. Please help me.

**Comment by adil06** [comment]
What should I do?

**Comment by rovo89** [comment]
I have no idea right now. You can try Xposed version 79 to see if it's any better, but I'm not so sure if it will help you.

**Comment by rovo89** [comment]
The key might be the ANRManager messsages, it seems that this is a vendor-specific services that sends a signal 16 to the system_server process, causing it to crash. Could you please upload your /system/framework folder so I can have a look at it?

**Comment by tigerwood** [comment]
I uploaded framework & also the whole system.img, please help to do further research, thanks!
framework: https://www.dropbox.com/s/j9e8su6m5cfbebn/framework.zip?dl=0
sytem.img: https://www.dropbox.com/s/r395e0a3fows9hh/system.zip?dl=0

**Comment by adil06** [comment]
Thanks @tigerwood. Dear @rovo89, please help us.

**Comment by rovo89** [comment]
I finally found some time to analyze this. As far as I could see, they indeed trigger the Signal 16 error deliberately and then catch and ignore it. Looks very strange to me, but anyway, here's a try to do the same:
https://www.dropbox.com/s/hn5ysl6zx8pe6kq/xposed-v80-sdk22-arm-test1.zip?dl=0
https://www.dropbox.com/s/rzgp8qji9bqyibn/xposed-v80-sdk22-arm64-test1.zip?dl=0

**Comment by happyBOY78** [comment]
Thank you @rovo89 for test version of v80 for arm.
I had the same problem as @adil06 on my "china phone" Doogee X5 with Lollipop 5.1 and xposed-v79-sdk-22-arm-zip
I try test version and xposed working perfectly, without any problem.

**Comment by tigerwood** [comment]
Thanks @rovo89 , it's worked for me also,
but there some performance issues, like if i call out, the sreen will more slowly change to the call screen compare to no xposed version, is there any possible to figure out it, thanks!

**Comment by rovo89** [comment]
> but there some performance issues, like if i call out, the sreen will more slowly change to the call screen compare to no xposed version, is there any possible to figure out it, thanks!

Performance issues are always very hard to analyze as they depend on so many factors and are often subjective. Sometimes, something as simple as a reboot helps. So I doubt that I can do anything for you in this regard.

**Comment by rovo89** [comment]
Fixed in v80.

**Comment by dissidius** [comment]
please any news for xiaomi redmi note 2 helio mtk 6795 i tried on latest miui 7.1.x.0 but still bootloop even with v80 please help

**Comment by smpranto** [comment]
I am using Symphony Helio S1, MT6753, 64 bit, malT-720, Android-5.1.1.
I have ROOT my device, installed Busibox. Flashed Xposed_framework v80_arm22.Zip via TWRP recovery. I have been made restart my device after every flashed and apk installed.
But, xposed installer always say me, Framework installed but not active.
I was checked the config folder the is no disabled log file.
Plz help me. If you want i can provide you every screenShot via email. You just allow me to know your E-Mail address.

Thank you!!

**Comment by truedied** [comment]
05-06 10:50:07.272 I/Xposed  (  318): -----------------
05-06 10:50:07.272 I/Xposed  (  318): Starting Xposed version 84, compiled for SDK 22
05-06 10:50:07.272 I/Xposed  (  318): Device: Redmi Note 2 (xiaomi), Android version 5.1.1 (SDK 22)
05-06 10:50:07.272 I/Xposed  (  318): ROM: Hermes-Resurrection-Remix-5.1.1-LMY48Y-20160318
05-06 10:50:07.272 I/Xposed  (  318): Build fingerprint: xiaomi/cm_hermes/hermes:5.1.1/LMY48Y/3ee5082a38:userdebug/test-keys
05-06 10:50:07.272 I/Xposed  (  318): Platform: arm64-v8a, 64-bit binary, system server: yes
05-06 10:50:07.272 I/Xposed  (  318): SELinux enabled: yes, enforcing: no
05-06 10:50:10.046 I/Xposed  (  318): -----------------
05-06 10:50:10.048 I/Xposed  (  318): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
05-06 10:50:10.157 I/Xposed  (  318): Forcing image recompilation because /data/dalvik-cache/arm64/system@framework@boot.art is not compiled for the current Xposed version
05-06 10:50:16.054 I/Xposed  (  320): -----------------
05-06 10:50:16.054 I/Xposed  (  320): Starting Xposed version 84, compiled for SDK 22
05-06 10:50:16.054 I/Xposed  (  320): Device: Redmi Note 2 (xiaomi), Android version 5.1.1 (SDK 22)
05-06 10:50:16.054 I/Xposed  (  320): ROM: Hermes-Resurrection-Remix-5.1.1-LMY48Y-20160318
05-06 10:50:16.054 I/Xposed  (  320): Build fingerprint: xiaomi/cm_hermes/hermes:5.1.1/LMY48Y/3ee5082a38:userdebug/test-keys
05-06 10:50:16.054 I/Xposed  (  320): Platform: arm64-v8a, 32-bit binary, system server: no
05-06 10:50:16.054 I/Xposed  (  320): SELinux enabled: yes, enforcing: no
05-06 10:50:19.145 I/Xposed  (  320): -----------------
05-06 10:50:19.145 I/Xposed  (  320): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
05-06 10:50:19.212 I/Xposed  (  320): Forcing image recompilation because /data/dalvik-cache/arm/system@framework@boot.art is not compiled for the current Xposed version
05-06 10:50:27.357 I/Xposed  (  318): Detected ART runtime
05-06 10:50:27.377 I/Xposed  (  318): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
05-06 10:50:27.591 E/Xposed  (  318): Cannot load any modules because /data/data/de.robv.android.xposed.installer/conf/modules.list was not found
05-06 10:50:37.247 I/Xposed  (  320): Detected ART runtime
05-06 10:50:37.250 I/Xposed  (  320): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
05-06 10:50:37.334 E/Xposed  (  320): Cannot load any modules because /data/data/de.robv.android.xposed.installer/conf/modules.list was not found
05-06 11:03:14.297 W/Xposed  ( 9130): Package name for /data/app/com.internet.speed.meter.lite-1/base.apk had to be retrieved via parser
05-06 11:04:38.616 W/Xposed  (12018): Package name for /system/priv-app/SystemUI/SystemUI.apk had to be retrieved via parser
05-06 11:05:24.763 W/Xposed  (13455): Package name for /system/priv-app/SystemUI/SystemUI.apk had to be retrieved via parser
