### ISSUE TITLE
Frequent random reboots [Nexus 5]

### ISSUE THREAD

**Issue by sharathdaniel** [rovo89/Xposed#96]
For past two weeks i'm having random reboots in my Nexus 5 with Cataclysm ROM( a ROM based on stock google image), sometimes many reboots in a day. It's been running fine before, i don't know whats causing it. I haven't installed any other mods recently. I'm not sure if it's even related to xposed. The modules i'm using are bootmanager, greenify, max lock. Here are the logcats, i don't know if they're useful.

Log1: https://www.dropbox.com/s/pqlptfpcrhd3fdt/test.txt?dl=0
Log2: https://www.dropbox.com/s/8k5cfi7jm1qvygk/test2.txt?dl=0
Log3: https://www.dropbox.com/s/eg9ro78uama4p2y/reboot.txt?dl=0

**Comment by sharathdaniel** [comment]
Anybody?

**Comment by rovo89** [comment]
Sorry, I'm still busy with other issues.

Anyway, a quick look at the logs showed that they're not helpful for the analysis as they were taken too late. In order to check whether this is even related to Xposed, I need to see the crash which triggers the reboot.

As a first step, please check if you can find a pattern when the reboot occurs. If it's just "random", you'll have a hard time getting a good log. Once you can cause the reboot to happen, you can just execute "adb shell logcat -v time > logcat.txt", then trigger the crash, wait a few seconds and press Ctrl+C. Otherwise, you'll probably have to execute this command and wait until the crash happens.

**Comment by rovo89** [comment]
I'll close this issue as invalid/unrelated for now. If you can come up with better logs and more details, feel free to reopen. Please make sure to always use the latest version (v79 is out now).
